# Generated by Django 4.2.1 on 2023-06-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_tax_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_peice',
            new_name='discount_price',
        ),
    ]
