# Generated by Django 4.2.1 on 2023-06-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_discount_peice_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
