# Generated by Django 3.2 on 2023-06-09 13:07

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='timestamp',
            field=models.DateField(blank=True, null=True, validators=[products.validators.validate_timestamp]),
        ),
    ]
