# Generated by Django 4.2.1 on 2023-06-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books'),
        ),
    ]
