# Generated by Django 3.2 on 2023-06-12 13:02

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.image_upload_company),
        ),
        migrations.AddField(
            model_name='product',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.image_upload_company),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.image_upload_image),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.image_upload_image),
        ),
    ]
